# Generated by Django 3.2.9 on 2021-11-30 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='slug',
        ),
    ]
