# Generated by Django 3.2.9 on 2021-11-30 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_remove_thread_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
            ],
        ),
    ]
